# Generated by Django 4.2.7 on 2023-11-15 04:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_in_time', models.DateTimeField(null=True)),
                ('log_out_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='email', max_length=200, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('firstname', models.CharField(default='firstname', max_length=100)),
                ('lastname', models.CharField(default='lastname', max_length=100)),
                ('password', models.CharField(default='pwd', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('page_visit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(default='PageName', max_length=100)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('time_spent', models.DateTimeField(null=True)),
                ('log_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UsersApp.logs')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UsersApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='logs',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UsersApp.user'),
        ),
    ]
