# # The docker-compose.yml file describes the services that make your app. In this example those services are a web server and database.

# version: "3.9"
   
# services:
#     web:
#         image: django-docker:0.0.1
#         build: .
#         ports:
#             - "8000:8000"
#         depends_on:
#             - pgdb
#     pgdb:
#         image: postgres
#         # container_name: pgdb
#         # environment:
#         # - POSTGRES_DB=postgres
#         # - POSTGRES_USER=postgres
#         # - POSTGRES_PASSWORD=postgres
# version: '3.9'

# services:
#     db:
#         image: postgres:13.4-alpine
#     web:
#         build: .
#         volumes:
#             - .:/code
#         ports:
#             - "8000:8000"
#         depends_on:
#             - db
    

version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:12.0
    environment:
      - POSTGRES_DB=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}

    
